# From RiotX, thanks to everyone there! https://github.com/vector-im/riotX-android

# Use Docker file from https://hub.docker.com/r/runmymind/docker-android-sdk
# Last docker plugin version can be found here:
# https://github.com/buildkite-plugins/docker-buildkite-plugin/releases
# We propagate the environment to the container (sse https://github.com/buildkite-plugins/docker-buildkite-plugin#propagate-environment-optional-boolean)

steps:
  - label: "Compile and run library Unit tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # gradle build can be memory hungry
      queue: "medium"
    commands:
      - "./gradlew :laputacloudslib:clean :laputacloudslib:test --stacktrace"
    plugins:
      - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"
          propagate-environment: true

  - label: "Compile and run library Android tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # gradle build can be memory hungry
      queue: "medium"
    commands:
      - "./gradlew :laputacloudslib:clean :laputacloudslib:assembleAndroidTest --stacktrace"
    plugins:
      - docker#v3.1.0:
          image: "runmymind/docker-android-sdk"
          propagate-environment: true

  # Code quality
  - label: "ktlint"
    command:
      - "./gradlew :laputacloudslib:clean :laputacloudslib:ktlint --stacktrace"
    plugins:
      - docker#v3.1.0:
          image: "openjdk"
